[project]
name = "bibtex-entry-picker"
version = "0.1.0"
description = "BibTeXのエントリを文字列に整形してクリップボードにコピーするもの"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pybtex>=0.25.1",
    "pyperclip>=1.11.0",
    "regex>=2025.10.23",
]
